version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=ecommerce_spider
      - POSTGRES_USER=ecommerce_spider_admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin4_scraper
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8088:80"
    networks:
      - postgres
volumes:
  db:
    driver: local
networks:
  postgres:
    driver: bridge
